apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    name: front-service
    app: demo-front-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
   
  selector:
    name: front-app-pod
    app: demo-front-app
    
